import type { Offer, Product } from "./types";

function img(category: Product["category"], seed: number): string {
  return `placeholder:${category}:${seed}`;
}

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "sample-1",
    name: "Vestido Florencia",
    category: "indumentaria",
    subcategory: "Vestidos",
    images: [img("indumentaria", 0), img("indumentaria", 1)],
    description:
      "Vestido liviano de corte suelto, ideal para el día a día. Estampa floral delicada y caída fresca.",
    availability: "en_stock",
    hidden: false,
    created_at: "2026-06-01T12:00:00Z",
  },
  {
    id: "sample-2",
    name: "Sweater Trenzado Otoño",
    category: "indumentaria",
    subcategory: "Sweaters",
    images: [img("indumentaria", 2)],
    description: "Sweater tejido con trenzas, cuello redondo y calce oversize. Abriga sin pesar.",
    availability: "ultimas_unidades",
    hidden: false,
    created_at: "2026-05-20T12:00:00Z",
  },
  {
    id: "sample-3",
    name: "Campera Urbana Impermeable",
    category: "indumentaria",
    subcategory: "Camperas",
    images: [img("indumentaria", 3)],
    description: "Campera liviana con capucha, resistente al agua liviana. Perfecta para entretiempo.",
    availability: "en_stock",
    hidden: false,
    created_at: "2026-05-10T12:00:00Z",
  },
  {
    id: "sample-4",
    name: "Perfume Ámbar Nocturno",
    category: "perfumeria",
    subcategory: "Perfumes",
    images: [img("perfumeria", 0)],
    description: "Fragancia amaderada con notas de ámbar y vainilla. Larga duración, ideal para la noche.",
    availability: "en_stock",
    hidden: false,
    created_at: "2026-06-05T12:00:00Z",
  },
  {
    id: "sample-5",
    name: "Colonia Floral Suave",
    category: "perfumeria",
    subcategory: "Colonias",
    images: [img("perfumeria", 1)],
    description: "Colonia fresca de notas florales suaves, perfecta para uso diario.",
    availability: "en_stock",
    hidden: false,
    created_at: "2026-04-15T12:00:00Z",
  },
  {
    id: "sample-6",
    name: "Crema Hidratante Corporal",
    category: "cremas",
    subcategory: "Corporal",
    images: [img("cremas", 0)],
    description: "Crema de textura liviana con manteca de karité. Hidrata profundo sin dejar sensación grasa.",
    availability: "en_stock",
    hidden: false,
    created_at: "2026-06-10T12:00:00Z",
  },
  {
    id: "sample-7",
    name: "Crema Facial Nutritiva",
    category: "cremas",
    subcategory: "Facial",
    images: [img("cremas", 1)],
    description: "Crema facial con vitamina E, para piel seca a mixta. Uso diario mañana y noche.",
    availability: "agotado",
    hidden: false,
    created_at: "2026-03-01T12:00:00Z",
  },
  {
    id: "sample-8",
    name: "Set Tuppers Herméticos x4",
    category: "tuppers",
    subcategory: "Cocina",
    images: [img("tuppers", 0)],
    description: "Juego de 4 tuppers herméticos apilables, aptos para freezer, microondas y lavavajillas.",
    availability: "en_stock",
    hidden: false,
    created_at: "2026-05-28T12:00:00Z",
  },
  {
    id: "sample-9",
    name: "Tupper Térmico Vianda",
    category: "tuppers",
    subcategory: "Viandas",
    images: [img("tuppers", 1)],
    description: "Vianda térmica con cierre hermético, mantiene la temperatura por varias horas.",
    availability: "ultimas_unidades",
    hidden: false,
    created_at: "2026-04-22T12:00:00Z",
  },
  {
    id: "sample-10",
    name: "Bolso Tote de Verano",
    category: "varios",
    subcategory: "Bolsos",
    images: [img("varios", 0)],
    description: "Bolso amplio de lona resistente, con bolsillo interior. Combina con todo.",
    availability: "en_stock",
    hidden: false,
    created_at: "2026-06-15T12:00:00Z",
  },
  {
    id: "sample-11",
    name: "Cartuchera de Cuero Ecológico",
    category: "varios",
    subcategory: "Accesorios",
    images: [img("varios", 1)],
    description: "Cartuchera compacta de cuero ecológico, ideal para uso diario o de estudio.",
    availability: "en_stock",
    hidden: false,
    created_at: "2026-02-18T12:00:00Z",
  },
  {
    id: "sample-12",
    name: "Remera Básica Algodón",
    category: "indumentaria",
    subcategory: "Remeras",
    images: [img("indumentaria", 4)],
    description: "Remera de algodón peinado, corte clásico. Se consigue en varios colores.",
    availability: "en_stock",
    hidden: false,
    created_at: "2026-06-18T12:00:00Z",
  },
];

export const SAMPLE_OFFERS: Offer[] = [
  {
    id: "sample-offer-1",
    title: "Novedades de la semana",
    product_ids: ["sample-1", "sample-4", "sample-8", "sample-10"],
    starts_at: "2026-06-01T00:00:00Z",
    ends_at: null,
    position: 0,
  },
  {
    id: "sample-offer-2",
    title: "Últimas unidades",
    product_ids: ["sample-2", "sample-9"],
    starts_at: "2026-06-01T00:00:00Z",
    ends_at: "2026-12-31T23:59:59Z",
    position: 1,
  },
];
